### ISSUE TITLE
Don't use outdated version in README.md

### ISSUE THREAD

**Issue by hubx** [tiagoboldt/sharelatex-docker#10]
Hi, thanks for the Dockerfile

I followed the readme. At

> docker run -d -p 3000:3000 tiagoboldt/sharelatex-docker:sharelatex sharelatex.sh

The problem was mongodb was slow to startup as a result sharelatex didn't start. You fixed this in d83beae007180f54592815a4f9ea4c52677e8d15 however the sharelatex docker registry tag is outdated.

Either update the docker registry tag or switch to 
> docker run -d -p 3000:3000 tiagoboldt/sharelatex-docker sharelatex.sh

in the README.md

**Comment by tiagoboldt** [comment]
@hubx would you like to submit a pull request for this?

**Comment by hubx** [comment]
Ok. I thought you may want to decide wether to update the docker registry tag or the README. PR #11 should fix this.
