### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by DarkDirk** [tiagoboldt/sharelatex-docker#16]
Do we want spell checking in the docker container? At least for english? The official container has all the aspell packages installed. Should I also add them?

**Comment by tiagoboldt** [comment]
makes sense :)

On Thu, Apr 23, 2015 at 5:42 PM, Dirk Heinke <notifications@github.com>
wrote:

> Do we want spell checking in the docker container? At least for english?
> The official container has all the aspell packages installed. Should I also
> add them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoboldt/sharelatex-docker/issues/16>.
>



-- 
Tiago Boldt Sousa
Assistant Lecturer - Faculdade de Engenharia da Universidade do Porto
