### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by luwidmer** [tiagoboldt/sharelatex-docker#18]
Hi guys
I noticed that bunyan uses more and more memory as you compile LaTeX documents - this seems to be the same issue as in https://github.com/sharelatex/web-sharelatex/issues/67 - would it be possible to replace the "grunt run" part with the upstart scripts provided by the sharelatex guys?

**Comment by tiagoboldt** [comment]
Makes sense. Let's change the run script with the details from here: https://github.com/sharelatex/sharelatex/wiki/Production-Installation-Instructions

**Comment by DarkDirk** [comment]
It won't work that easy way, because we have no upstart in containers. So there are two ways

1. run the services without bunyan and pipe the output to a file on the volume
2. change the whole docker container to use the same base image which the official docker container uses and use thiere startscripts for runit

**Comment by tiagoboldt** [comment]
The first approach is more like an hack, while the second is a solution. I
would suggest that we go with that one!

On Tuesday, May 26, 2015, Dirk Heinke <notifications@github.com> wrote:

> It won't work that easy way, because we have no upstart in containers. So
> there are two ways
>
>    1. run the services without bunyan and pipe the output to a file on
>    the volume
>    2. change the whole docker container to use the same base image which
>    the official docker container uses and use thiere startscripts for runit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoboldt/sharelatex-docker/issues/18#issuecomment-105652808>
> .
>


-- 
Tiago Boldt Sousa
Assistant Lecturer - Faculdade de Engenharia da Universidade do Porto
