### ISSUE TITLE
Version 0.2.0

### ISSUE THREAD

**Issue by luwidmer** [tiagoboldt/sharelatex-docker#20]
Release 0.2.0 seems to be out - did anyone try it out yet? I couldn't find a changelog, but it's there.

**Comment by DirkHeinke** [comment]
I haven't tried yet, but maybe it's enough to just change the branch we use? I'm a bit busy right now, but I'll test it later this month if no one else send a PR ;-)

**Comment by DirkHeinke** [comment]
I updated the Dockerfile. The official build should update soon.
