### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by Apidcloud** [tiagoboldt/sharelatex-docker#26]
Good evening,

I am trying to follow the README steps, but the docker is not running correctly.
I have done the following:
`docker pull  tiagoboldt/sharelatex-docker
mkdir /srv/sharelatex-data
docker run -d -p 3000:3000 -v /srv/sharelatex-data:/data tiagoboldt/sharelatex-docker`

The last command is printing the container ID and starting it. Shouldn't mongodb and redis be listed when doing docker ps, too? After 10 seconds, the container goes off. Thus, when I try to open localhost:3000, nothing happens.

Am I doing something wrong?

Here's a pastebin of the docker run command without the background flag (-d):
http://pastebin.com/YBYsC7Vv

Sincerely,
Apidcloud

**Comment by m-schmoock** [comment]
I think this should be fixed by already merged pull #27 
https://github.com/tiagoboldt/sharelatex-docker/pull/27

Can you retry with an updated image.

**Comment by Apidcloud** [comment]
I have also tried to build the image from the source code. Also didn't work.

**Comment by m-schmoock** [comment]
Okay, if its not fixed, please check the logfiles, in your case located at:

    /srv/sharelatex-data/logs/*

If the service stops running there should be some error message.

**Comment by christianreiss** [comment]
v8-profiler is now in the current sharelatex distribution; I tested this with the recent Dockerfile update.
If the error persist, please re-open this issue.

Closing this issue now.
