### ISSUE TITLE
persistent data

### ISSUE THREAD

**Issue by puterleat** [tiagoboldt/sharelatex-docker#6]
For those new to docker, it would help to add a note in the docs on how to configure with for persistent data in a few common scenarios — e.g. self hosting on a single VPS like digitalocean.

At the least, it would help to explain that data (user accounts, projects) will not persist across restarts of the docker instance.

**Comment by hubx** [comment]
Maski (comment here https://registry.hub.docker.com/u/tiagoboldt/sharelatex-docker/) suggested

> docker run -d -p 3000:3000 -v host_folder:/data/db tiagoboldt/sharelatex-docker sharelatex.sh

I would suggest add to the README.md

> mkdir /srv/sharelatex-data
> docker run -d -p 3000:3000 -v /srv/sharelatex-data:/data/ tiagoboldt/sharelatex-docker sharelatex.sh

**Comment by tiagoboldt** [comment]
@hubx please create a pull request with that change, I'll gladly accept it.

**Comment by danijel3** [comment]
I noticed one more problem. When I run the image for the first time, it throws an error that it's missing /data/db directory. Not sure if that is the right thing to do, but adding an "mkdir /srv/sharelatex-data/db" after the first mkdir seems to fix this problem.

**Comment by tiagoboldt** [comment]
please submit a pull request with proposed changes.
